<a href="https://colab.research.google.com/github/jpaulorc/machine_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

In [4]:
my_list = [i for i in range(10000000)]
start_time = process_time()
my_list = [i+5 for i in my_list]
end_time = process_time()

print(end_time - start_time)

0.9331732820000003


In [5]:
np_array = np.array([i for i in range(10000000)])
start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.009871897000000018


Initial Placeholders in numpy arrays

In [6]:
# create a numpy array of zeros
x = np.zeros((3,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# create a numpy array of ones
z = np.ones((3,2))
print(z)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# create a numpy array of a particular value
a = np.full((5,4), 6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [9]:
# create an identity matrix
s = np.eye(7)
print(s)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [10]:
# create a numpy array with random values
b = np.random.random((3,5))
print(b)

[[0.30231389 0.67531379 0.35475405 0.14286904 0.16583342]
 [0.79507136 0.11951955 0.85319579 0.27289659 0.29207761]
 [0.63928093 0.92273239 0.23832931 0.60872705 0.61556901]]


In [12]:
# create a random integer values array within a specific range
c = np.random.randint(10,50,(3,5))
print(c)

[[14 43 41 28 13]
 [12 28 47 21 33]
 [25 17 30 26 43]]


In [20]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,50,6)
print(d)

[10. 18. 26. 34. 42. 50.]


In [22]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,3)
print(e)

[10 13 16 19 22 25 28]


In [23]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray